//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFstokTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> StokAdedi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> KategoriId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
